---
# Ansbile Controller Ubuntu
- name: controller
  ami: ami-34332854

# Centos Load Balancer
- name: load-Balancer
  ami: ami-34332854

# Centos Rails Servers
- name: rails-1
  ami: ami-df2932bf

- name: rails-2
  ami: ami-df2932bf

# Centos PostgresDB Server
- name: pg
  ami: ami-df2932bf
