---
- name: ansible-control
  box: ubuntu/xenial64
  ip: 10.0.15.10
  foward_port:

- name: pg-1
  box: centos/7
  ip: 10.0.15.31
  foward_port: 8081

- name: pg-2
  box: centos/7
  ip: 10.0.15.32
  foward_port: 8082

- name: pg-3
  box: centos/7
  ip: 10.0.15.33
  foward_port: 8082

- name: ha-proxy
  box: centos/7
  ip: 10.0.15.40
  foward_port: false

- name: etcd
  box: centos/7
  ip: 10.0.15.41
  foward_port: false

#- name: nginx-lb
  #box: ubuntu/xenial64
  #ip: 10.0.15.11
  #foward_port: 8080
  #script:
#- name: rails-1
  #box: ubuntu/xenial64
  #ip: 10.0.15.21
  #foward_port:
  #script:
#- name: rails-2
  #box: ubuntu/xenial64
  #ip: 10.0.15.22
  #foward_port:
  #script:
