---
# Ansbile Controller Ubuntu
- name: controller
  ami: ami-34332854

# Centos Load Balancer
- name: load-Balancer
  ami: ami-34332854

# Centos Rails Servers
- name: rails-1
  ami: ami-20f6ed40

- name: rails-2
  ami: ami-20f6ed40

# Centos PostgresDB Server
- name: pg
  ami: ami-20f6ed40
