---
- hosts: dbservers
  become: yes
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: Install postgres
      package:
        name:
          - postgresql-server
          - postgresql-contrib

    - name: Enable PG service
      service: name=postgresql
               enabled=yes
               state=started

    - name: Install patroni dependencies
      package:
        name:
          - python
          - python-pip

    - name: instal patroni
      pip:
        name:
          - setuptools
          - patroni
        extra_args: --upgrade
