---
- hosts: dbservers
  become: yes
  gather_facts: false
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Install postgres
      package:
        name:
          - postgresql-server
          - postgresql-contrib

    - name: Enable PG service
      service: name=postgresql
               enabled=yes
               state=started

    - name: Install patroni dependencies
      package:
        name:
          - python
          - python-pip

    - name: upgrade setuptools
      pip:
        name:
          - setuptools
          - patroni
          - pip
        state: latest
