---
- hosts: dbservers
  become: yes
  gather_facts: false
  tasks:
    - name: Install epel-release & python devel
      yum:
        name:
          - epel-release
          - python-devel
        state: present
        update_cache: yes

    - name: install the 'Development tools' package group
      yum:
        name: "@Development tools"
        state: present

    - name: Install postgres
      package:
        name:
          - postgresql-server
          - postgresql-contrib

    - name: Create database
      command: postgresql-setup initdb
               creates=/var/lib/pgsql/data/postgresql.conf

    - name: Enable PG service
      service: name=postgresql
               enabled=yes
               state=started

    - name: Install patroni dependencies
      package:
        name:
          - python
          - python-pip

    - name: Install Patroni and upgrade pip/setuptools
      pip:
        name:
          - setuptools
          - patroni
          - pip
        state: latest

    - name: Update Patroni configuration
      template:
        src: patroni.yml.j2
        dest: /etc/patroni.yml
        mode: 0744

    - name: Create Patroni dirs
      file:
        path: /data/patroni
        state: directory
        owner: postgres
        group: postgres
        mode: 0700
        recurse: yes

    - name: Create Patroni service
      template:
        src: patroni.service.j2
        dest: /etc/systemd/system/patroni.service
        owner: root
        group: root
        mode: 0755

    - name: Enable Patroni service
      service: name=patroni
               enabled=yes
               state=started
