---
- hosts: [rails]
  tasks:
    - name: Install git
      become: yes
      yum:
        name: git-core
        state: present

    - name: Clone repo
      become: yes
      git:
        repo: https://github.com/ivaldi/brimir.git
        dest: /var/www/brimir

    - name: Install bundler gem
      command: ~/.rbenv/shims/gem install bundler
      args:
        creates: ~/.rbenv/shims/bundler

    - name: Install App Gems
      bundler:
        state: present
        executable: ~/.rbenv/shims/bundle
        chdir: /var/www/brimir
