---
- hosts: [rails]
  tasks:
    - name: Install git
      become: yes
      yum:
        name: git-core
        state: present

    - name: Clone repo
      become: yes
      git:
        repo: https://github.com/ivaldi/brimir.git
        dest: /var/www/brimir

    - name: Check app dir ownership
      become: yes
      file:
        path: /var/www/brimir
        recurse: true
        owner: ansible
        group: ansible

    - name: Install bundler gem
      command: ~/.rbenv/shims/gem install bundler
      args:
        creates: ~/.rbenv/shims/bundler

    - name: Install App Gems
      bundler:
        state: present
        executable: ~/.rbenv/shims/bundle
        extra_args: --without sqlite mysql development test --deployment
        chdir: /var/www/brimir

    - name: Create database.yml file
      template:
        src: database.yml.j2
        dest: /var/www/brimir/config/database.yml
